# Settings that the LAMMPS build will import when this package library is used
CUDA_FLAGS := -I/include -DUNIX  -DNO_PREC_TIMING -DFFT_CUFFT -DCUDA_PRECISION=2 -DCUDA_ARCH=20
CUDA_USRLIB_CONDITIONAL := -L/lib -L/lib64 -lcufft
 
user-cuda_SYSINC = ${CUDA_FLAGS}
user-cuda_SYSLIB =  -lcufft -lcuda -lcudart 
user-cuda_SYSPATH = $(CUDA_USRLIB_CONDITIONAL)
